### ISSUE TITLE
Balance out seagull killing

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/fishingmod#8]
Right now, one person can steal seagulls just with a simple E2/Starfall chip and a Wire Turret. I feel this should be changed to where if the inflictor is a turret or anything that can be automated to kill gives the seagull kill to whoever it spawned for, but a normal weapon kill makes it still up for grabs by whoever killed it.

**Comment by Etothepowerof26** [comment]
Could be a possibility. Going to do some testing later on to help this problem
